### ISSUE TITLE
No connection to my local hosted supbabase/auth instance on newer versions

### ISSUE THREAD

**Issue by BjoernRave** [supabase/auth-js#927]
As I already mentioned in: https://github.com/supabase/auth-js/issues/921

I have a locally hosted instance of gotrue/auth on version 2.153.0.

When running version 2.62.2 everything works fine.

When upgrading to the latest version I get 

`Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9999/token?grant_type=refresh_token. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 204` in the browser and when i check the console of the docker container I see no requests.

I didn't change anything but the version of auth-js

**Comment by BjoernRave** [comment]
just tested again and the regression is also present in `2.63.2`

**Comment by J0** [comment]
Hey @BjoernRave,

Thanks, I would guess that the issue is more closely linked to the Auth server rather than the client lib. Auth runs on `http://localhost:9999` by default so it will likely block anything running on other ports unless CORS is set to allow it. If you are debugging / testing locally with a Next.js application you can modify [this line](https://github.com/supabase/auth/blob/2d519569d7b8540886d0a64bf3e561ef5f91eb63/internal/api/api.go#L329)

With the following:

```
corsHandler := cors.New(cors.Options{
             AllowedOrigins:   []string{"http://localhost:3000"},
             AllowedMethods:   []string{http.MethodGet, http.MethodPost, http.MethodPut, http.MethodDelete},
               AllowedHeaders:   globalConfig.CORS.AllAllowedHeaders([]string{"Accept", "Authorization", "Content-Type", "X-Client-IP", "X-Client-Info", "x-supabase-api-version", audHeaderName, useCookieHeader}),
                ExposedHeaders:   []string{"X-Total-Count", "Link"},
                AllowCredentials: true,
                Debug:            true,
        })
```

Let me know if this works for you

**Comment by BjoernRave** [comment]
yeah, the issue can be closed. The reason was that my `supbabase/auth` container was still on `v2.153.0`, which apparently wasnt compatible with `@supabase/auth-js` 2.64.4 or any other version wbich supported anonymous users. upgrading the container to v2.158.1 solved the issue.
